My first pull request
phelian23/Hello-World pull request #1
Opened 2021-09-14 12:09 UTC by phelian23

2021-09-14 12:25 UTC, dasileker requested changes
### **Hi @phelian23,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-14 12:25 UTC, dasileker commented on index.html
> +</html>
- [ ] This is causing linters error, please add  linters to your project to fix the issue before send a PR for review [ HTML/CSS linters link](https://github.com/microverseinc/linters-config)

2021-09-14 12:25 UTC, dasileker commented on test.md
> +This file should be ignored by git
- [ ] the test.md should not be visible after adding it to the gitignore file.

2021-09-14 12:25 UTC, dasileker commented on styles.css
> +    color: blue;
- [ ] Also your style is having linters error so doo the same here, add style linter file to fix all issue before sending it for review.

2021-09-15 06:47 UTC, mke2111 approved these changes
### Hi @phelian23, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 06:51 UTC, merged